config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home' => 'pages#home'

  resources :users

  resources :albums do
    resources :photos
  end
  
  get 'browse_albums' => 'albums#browse'

  get 'register' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  get 'logout' => 'logins#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 80 }
  validates :user_id, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  validates :user_id, presence: true
  validates :tag_line, length: { maximum: 150 }
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :photos
  before_save { self.email = email.downcase }
  validates :name, presence: :true, length:  { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: :true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_action :set_album, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :browse]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @albums = Album.where(user: current_user).paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.create(album_params)
    @album.user = current_user
    if @album.save
      flash[:success] = 'Album Created!'
      redirect_to album_path(@album) # TO DO change to show album page
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @album.update(album_params)
      flash[:success] = "Album Details Updated"
      redirect_to album_path(@album)
    else
      render :edit
    end
  end
  
  def show
    
  end
  
  def destroy
    @album.destroy
    flash[:success] = 'Album Deleted!'
    redirect_to albums_path
  end
  
  def browse
    @albums = Album.where(private: false).order('created_at desc').paginate(page: params[:page], per_page: 25)
    respond_to do |format|
      format.html
      format.json { render json: @albums }
    end
  end
  
  private
  
    def album_params
      params.require(:album).permit(:name, :private)
    end
    
    def set_album
      @album = Album.find(params[:id])
    end
    
    def require_same_user
      if current_user != @album.user
        flash[:danger] = "You can edit only your albums!"
        redirect_to albums_path
      end
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = 'You must logged in to perform this action'
      redirect_to home_path
    end
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You are logged in."
      redirect_to albums_path
    else
      flash[:danger] = 'Email or password does not match!'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out."
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController   < ApplicationController
  
  def home
    public_albums = Album.where(private: false)
    @photos = Photo.where('album_id IN (?)', public_albums.ids).order('created_at desc').limit(25)
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :set_album
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @photo = Photo.new
  end
  
  def create
    if @album.photos.count <= 25 
      @photo = Photo.new(photo_params)
      @photo.album = @album
      @photo.image = params[:file]
      @photo.user = current_user
      @photo.save!
      render json: @photo
    else
      render json: { error: 'You have reached the limit of 25 images per album.' }
    end
  end
  
  def show
    
  end
  
  def edit
  
  end
  
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { 
          flash[:success] = 'Image details saved!'
          redirect_to edit_album_photo_path(@album, @photo)
        }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @photo.destroy
    redirect_to :back
  end
  
  private
  
    def set_album
      @album = Album.find(params[:album_id])
    end
    
    def set_photo
      @photo = Photo.find(params[:id])
    end
    
    def photo_params
      params.require(:photo).permit(:album_id, :image, :tag_line)
    end
    
    def require_same_user
      if current_user != @photo.user
        flash[:danger] = 'You can only edit your own photos!'
        redirect_to home_path
      end
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:index, :edit, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      # TODO store the user_id in session for future use
      flash[:success] = 'Your account has been successfully created! Please Log in.'
      redirect_to home_path
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = 'Your profile has been updated successfully!'
      redirect_to @user
    else
      render :edit
    end
  end
  
  def show
    if current_user == @user
      @albums = @user.albums.paginate(page: params[:page], per_page: 10)
    else
      @albums = @user.albums.where(private: false).paginate(page: params[:page], per_page: 10)
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:danger] = "Account Deleted!"
    redirect_to home_path
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
    
    def require_same_user
      if current_user != @user
        flash[:danger] = "You can only edit your own profile"
        redirect_to home_path
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for( user, options = { size: 80, class: '' } )
    gravatar_id = Digest::MD5::hexdigest( user.email )
    size = options[:size]
    classes = options[:class]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag( gravatar_url, alt: user.name, class: 'gravatar ' + classes )
  end
  
end

module Possessive
  def possessive
    suffix = if self.downcase == 'it'
      "s"
    elsif self.downcase == 'who'
      'se'
    elsif self.end_with?('s')
      "'"
    else
      "'s"
    end
    self + suffix
  end
end

class String
  include Possessive
end

app/views/albums/_form.html.erb
<!--<%= render 'shared/errors', obj: @album %>-->

<%= bootstrap_form_for @album do |f| %>
  
  <%= f.text_field :name %>
  
  <%= f.check_box :private, help: 'Tick if you want this album to be personal. Means only you can view its images' %>
  
  <%= f.submit(@album.new_record? ? 'Create Album':'Edit Album', class: 'btn btn-success btn-full-width') %>
  
<%- end %>

app/views/albums/browse.html.erb
<%= render 'shared/page_title', title: 'Browse Albums' %>

<%= will_paginate %>

<div class="row" id="albums">
  <%- if @albums.any? %>
    <%- @albums.each_with_index do |album, index| %>
      <div class="item col-lg-3 col-md-4 col-xs-6">
        <div class="card">
          <%= link_to album_path(album) do %>
            <%- if album.photos.any? %>
              <img class="card-img-top" src="<%= album.photos.first.image.url(:gallery_thumb).to_s %>" alt="<%= album.name.to_s %>">
            <%- else %>
              <img class="card-img-top" src="http://placehold.it/300x200" alt="placeholder">
            <%- end %>
          <%- end %>
          <div class="card-block">
            <h4 class="card-title"><%= link_to album.name, album_path(album) %></h4>
            <p class="card-text">
              <span class="small"><%= "created #{'with ' + pluralize(album.photos.count, 'photo') if album.photos.any?}" %> by <%= link_to album.user.name, user_path(album.user) %>, <%= "#{time_ago_in_words(album.created_at)} ago" %></span>
            </p>
            <%- if current_user == album.user %>
              <div class="btn-group card-actions" role="group" aria-label="Image Actions">
                <%= link_to edit_album_path(album), class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <%- end %> 
                <%= link_to album_path(album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <%- end %>
              </div>
            <%- end %>
          </div>
        </div>
      </div>
    <%- end %>
  <%- end %>
</div>

<%= will_paginate %>

<script type="text/javascript">
  $album_photos = $('#albums');

  // let isotope arrange images only after the images have been loaded, otherwise they are overlapped    
  $album_photos.imagesLoaded(function(){
    $album_photos.isotope({
      itemSelector: '.item',
      columnWidth: '.item'
    });
  });
  
  $('.card').hover(function(){
    $(this).find('.card-actions').show();
  }, function(){
    $(this).find('.card-actions').hide();
  });
  
</script>

app/views/albums/index.html.erb
<%= render 'shared/page_title', title: 'My Albums' %>

<%= will_paginate %>

<%= link_to new_album_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-plus"></span> New Album
<%- end %>

<hr/>

<div class="row" id="albums">
  <%- if @albums.any? %>
    <%- @albums.each_with_index do |album, index| %>
      <div class="item col-lg-3 col-md-4 col-xs-6">
        <div class="card">
          <%= link_to album_path(album) do %>
            <%- if album.photos.any? %>
              <img class="card-img-top" src="<%= album.photos.first.image.url(:gallery_thumb).to_s %>" alt="<%= album.name.to_s %>">
            <%- else %>
              <img class="card-img-top" src="http://placehold.it/300x200" alt="placeholder">
            <%- end %>
          <%- end %>
          <div class="card-block">
            <h4 class="card-title"><%= album.name %></h4>
            <p class="card-text">
              <span class="small"><%= "#{'has ' + pluralize(album.photos.count, 'photo') + ', ' if album.photos.any?}created #{time_ago_in_words(album.created_at)} ago" %></span>
            </p>
            <%- if current_user == album.user %>
              <div class="btn-group card-actions" role="group" aria-label="Image Actions">
                <%= link_to edit_album_path(album), class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <%- end %> 
                <%= link_to album_path(album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <%- end %>
              </div>
            <%- end %>
          </div>
        </div>
      </div>
    <%- end %>
  <%- end %>
</div>

<%= will_paginate %>

<script type="text/javascript">
  $album_photos = $('#album_photos');

  // let isotope arrange images only after the images have been loaded, otherwise they are overlapped    
  $album_photos.imagesLoaded(function(){
    $album_photos.isotope({
      itemSelector: '.item',
      columnWidth: '.item'
    });
  });
  
  $('.card').hover(function(){
    $(this).find('.card-actions').show();
  }, function(){
    $(this).find('.card-actions').hide();
  });
  
</script>

app/views/albums/show.html.erb
<%= render 'shared/page_title', title: @album.name %>

<div class="row">
  <div class="col-xs-12">  
    <span class="small">
      <%= "has #{pluralize(@album.photos.count, 'photo')}, created by #{@album.user.name}, #{time_ago_in_words(@album.created_at)} ago" %>
    </span>
    <hr />
    <%- if current_user == @album.user %>
      <div class="btn-group" role="group">
        <%= link_to edit_album_path(@album), class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-pencil"></span> Edit album
        <%- end %>
        <%= link_to album_path(@album), method: :delete, data: { confirm: 'All photos of this album will be deleted! Changes are irreversible. Are you sure?' }, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-trash"></span> Delete album
        <%- end %>
      </div>
      <% if @album.photos.count < 25 %>
        <%= link_to '#photo-dropzone', class: 'btn btn-default pull-right' do %>
          <span class="glyphicon glyphicon-plus"></span> Upload Photos
        <%- end %>
      <%- else %>
        <hr/>
        <div class="alert alert-danger">You have reached the limit of <strong>25</strong> images for this album. Delete some to add new.</div>
      <%- end %>
    <%- end %>
  </div>
</div>

<br/>

<div class="row" id="album_photos">
  <%- if @album.photos.any? %>
    <%- @album.photos.each_with_index do |photo, index| %>
      <div class="item col-lg-3 col-md-4 col-xs-6">
        <div class="card">
          <%= link_to photo.image.url.to_s, data: { lightbox: @album.name.parameterize, title: photo.tag_line.to_s } do %>
            <img class="card-img-top" src="<%= photo.image.url(:gallery_thumb).to_s %>" alt="<%= photo.tag_line.to_s %>">
          <%- end %>
          <div class="card-block">
            <h4 class="card-title"></h4>
            <p class="card-text">
              <%- unless photo.tag_line.blank? %>
                <b><%= photo.tag_line.to_s %></b>
              <%- else %>
                <b><%= (index+1).ordinalize %> Image</b>
              <%- end %>
              <br/>
              <span class="small"><%= "#{time_ago_in_words(photo.created_at)}" %> ago</span>
            </p>
            <%- if current_user == @album.user %>
              <div class="btn-group card-actions" role="group" aria-label="Image Actions">
                <%= link_to edit_album_photo_path(@album, photo), class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <%- end %> 
                <%= link_to album_photo_path(@album, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <%- end %>
              </div>
            <%- end %>
          </div>
        </div>
      </div>
    <%- end %>
  <%- end %>
</div>

<br />

<%- if current_user == @album.user %>
  <div class="row">
    <div class="col-xs-12">
      <%- if @album.photos.count < 25 %>
        <%= form_for [@album, Photo.new], :html => { id: 'photo-dropzone', class: :dropzone, multipart: true } do |f| %>
          <%= f.hidden_field :image %>
          <div class="dz-message needsclick">
            Drop files here or click to upload.
          </div>
        <%- end %>
      <%- end %>
    </div>
  </div>
<%- end %>

<script type="text/javascript">
  /** let isotope arrange images only after the images have been loaded,
   * otherwise they are overlapped
   */
  $album_photos = $('#album_photos');
  $album_photos.imagesLoaded(function(){
    $album_photos.isotope({
      itemSelector: '.item',
      columnWidth: '.item'
    });
  });
  
  /** Dropzone config options
   * Allow user to only upload upto 25 files per album
   */
  Dropzone.options.photoDropzone = {
    maxFiles: <%= 25 - @album.photos.count %>,
    maxFilesize: 5,
    acceptedFiles: 'image/*',
    init: function() {
      var dropzone = this;
      
      this.on('maxfilesexceeded ', function(){
        alert_html = '<div class="alert alert-danger alert-dismissable">' +
          '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
            '<span aria-hidden="true">&times;</span>' +
            'You can only upload max <strong>25</strong> files' +
          '</button></div>';
          console.log(dropzone, alert_html);
        dropzone.prepend(alert_html);
      });
    }
  };
  
  // The Actions button on the image card
  $('.card').hover(function(){
    $(this).find('.card-actions').show();
  }, function(){
    $(this).find('.card-actions').hide();
  });
  
  /** wrap around the images
   * If true, when a user reaches the last image in a set, the right navigation 
   * arrow will appear and they will be to continue moving forward which will 
   * take them back to the first image in the set.
   */
  lightbox.option({
    'wrapAround': true
  });
    
</script>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Copyright 2015 Parity Cube Pvt. Ltd.</p>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">PCISA</a>
    </div><!--/.navbar-header-->
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= browse_albums_path %>"><span class="glyphicon glyphicon-th"></span> Browse Albums</a></li>
        <%- if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Albums <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%- if current_user.albums.any? %>
                <%- current_user.albums.each do |album| %>
                  <li><a href="<%= album_path(album) %>"><span class="glyphicon glyphicon-picture"></span> <%= album.name %></a></li>
                <%- end %>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">ACTIONS</li>
              <%- end %>
              <li><a href="<%= albums_path %>"><span class="glyphicon glyphicon-list-alt"></span> My Albums</a></li>
              <li><a href="<%= new_album_path %>"><span class="glyphicon glyphicon-plus"></span> New Album</a></li>
            </ul>
          </li>
        <%- else %>
          <li><a href="<%= register_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <%- end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%- if logged_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= gravatar_for( current_user, size: 20, class: 'round profile-icon' ) %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= user_path(current_user) %>"><span class="glyphicon glyphicon-user"></span> View Profile</a></li>
              <li><a href="<%= edit_user_path(current_user) %>"><span class="glyphicon glyphicon-pencil"></span> Edit Profile</a></li>
              <li role="separator" class="divider"></li>
              <!--<li class="dropdown-header">Nav header</li>-->
              <li><a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
            </ul>
          <%- else %>
            <li><a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span>  Log in</a></li>
          <%- end %>
        </li>
      </ul><!--/.navbar-right-->
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</nav><!--/.navbar-->

app/views/pages/home.html.erb
<%= render 'shared/page_title', title: 'Latest...' %>

<div class="row" id="album_photos">
  <%- if @photos.any? %>
    <%- @photos.each_with_index do |photo, index| %>
      <div class="item col-lg-3 col-md-4 col-xs-6">
        <div class="card">
          <%= link_to photo.image.url.to_s, data: { lightbox: 'latest-25', title: photo.tag_line.to_s } do %>
            <img class="card-img-top" src="<%= photo.image.url(:gallery_thumb).to_s %>" alt="<%= photo.tag_line.to_s %>">
          <%- end %>
          <div class="card-block">
            <!--<h4 class="card-title"></h4>-->
            <p class="card-text">
              <b><%= photo.tag_line.to_s %></b>
              <br/>
              <span class="small">uploaded by <%= link_to photo.user.name, user_path(photo.user) %> in <%= link_to photo.album.name, album_path(photo.album) %>, <%= "#{time_ago_in_words(photo.created_at)} ago" %></span>
            </p>
            <%- if current_user == photo.user %>
              <div class="btn-group card-actions" role="group" aria-label="Image Actions">
                <%= link_to edit_album_photo_path(photo.album, photo), class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <%- end %> 
                <%= link_to album_photo_path(photo.album, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <%- end %>
              </div>
            <%- end %>
          </div>
        </div>
      </div>
    <%- end %>
  <%- end %>
</div>

<div class="well">
  <h1 class="center">You can also...</h1>
  <p class="center">Sign Up to create your own Unlimited Albums.</p>
  <%= link_to register_path, class: 'btn btn-success btn-full-width' do %>
    Sign Up now <span class="glyphicon glyphicon-chevron-right"></span>
  <%- end %>
</div>

<script type="text/javascript">
  /** let isotope arrange images only after the images have been loaded,
   * otherwise they are overlapped
   */
  $album_photos = $('#album_photos');
  $album_photos.imagesLoaded(function(){
    $album_photos.isotope({
      itemSelector: '.item',
      columnWidth: '.item'
    });
  });
  
  // The Actions button on the image card
  $('.card').hover(function(){
    $(this).find('.card-actions').show();
  }, function(){
    $(this).find('.card-actions').hide();
  });
  
</script>

app/views/photos/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Photo' %>

<div class="row">
  <div class="col-lg-12 col-md-12 col-xs-12">
    <%= bootstrap_form_for [@album, @photo] do |f| %>
  
      <div class="row">
        <div class="col-xs-6">
          <%= image_tag(@photo.image.url, alt: "#{@album.name} image ##{@photo.id.to_s}", class: 'img-responsive', data: { lightbox: @album.name.parameterize } ) if @photo.image? %>
        </div>
        <div class="col-xs-6">
          <%= f.text_field :tag_line, hide_label: false, append: f.submit('Save', class: 'btn btn-primary') %>
          
          <span class="small"><%= time_ago_in_words(@photo.created_at) %> ago in <b><%= link_to @album.name, album_path(@album) %></b></span>
          <hr/>
          <div class="btn-group" role="group">
            <%= link_to album_path(@album), class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-chevron-left"></span> <%= "Back to #{@album.name}" %>
            <%- end %>
            <%= link_to album_photo_path(@album, @photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
            <%- end %>
          </div>
        </div>
      </div>
      
    <%- end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row show_user_profile">
  
  <div class="col-lg-4 col-md-4 profile_information">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 profile_image center">
        <%= gravatar_for( @user, size: '100x100', class: 'round' ) %>
      </div>
      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 profile_details">
        <h3 class="user_name"><%= @user.name %></h3>
        <p class="user_email"><%= @user.email %></p>
        <span class="user_albums"><%= pluralize(@user.albums.count, 'album') %> and <%= pluralize(@user.photos.count, 'photo') %></span>
      </div>
    </div>
    <%- if current_user == @user %>
      <hr />
      <div class="row">
        <div class="col-lg-6 col-xs-6">
          <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary btn-full-width' %>
        </div>
        <div class="col-lg-6 col-xs-6">
          <%= link_to 'Log out', logout_path, class: 'btn btn-default btn-full-width' %>
        </div>
      </div>
    <%- end %>
  </div>
  
  <div class="col-lg-8 col-md-8">
    <div>
      <h1><%= (current_user == @user) ? 'My':'' %> Albums</h1>
      <hr />
      <%= link_to new_album_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-plus"></span> New Album
      <%- end %>
      
      <hr/>
    </div>
  
  
    <div id="albums_listing">
      <%- if @albums.any? %>
        <%= will_paginate @albums %>
        <%- @albums.each_with_index do |album, index| %>
          <div class="item col-lg-4 col-md-3 col-xs-6">
            <div class="card">
              <%= link_to album_path(album) do %>
                <%- if album.photos.any? %>
                  <img class="card-img-top" src="<%= album.photos.first.image.url(:gallery_thumb).to_s %>" alt="<%= album.name.to_s %>">
                <%- else %>
                  <img class="card-img-top" src="http://placehold.it/300x200" alt="placeholder">
                <%- end %>
              <%- end %>
              <div class="card-block">
                <h4 class="card-title"><%= album.name %></h4>
                <p class="card-text">
                  <span class="small"><%= "created #{'with ' + pluralize(album.photos.count, 'photo') if album.photos.any?} by #{album.user.name.to_s}, #{time_ago_in_words(album.created_at)} ago" %></span>
                </p>
                <div class="btn-group card-actions" role="group" aria-label="Image Actions">
                  <%= link_to edit_album_path(album), class: 'btn btn-default' do %>
                    <span class="glyphicon glyphicon-pencil"></span>
                  <%- end %> 
                  <%= link_to album_path(album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <%- end %>
                </div>
              </div>
            </div>
          </div>
        <%- end %>
      <%- end %>
      <%= will_paginate @albums %>
    </div>
  </div>

</div>


<script type="text/javascript">
  $album_photos = $('#albums_listing');

  // let isotope arrange images only after the images have been loaded, otherwise they are overlapped    
  $album_photos.imagesLoaded(function(){
    $album_photos.isotope({
      itemSelector: '.item',
      columnWidth: '.item'
    });
  });
  
  $('.card').hover(function(){
    $(this).find('.card-actions').show();
  }, function(){
    $(this).find('.card-actions').hide();
  });
  
</script>
  
  